-- Create a new table for 1NF
CREATE TABLE TBL_1NF (
    YEAR            VARCHAR(10),
    TERM            VARCHAR(10),
    PROGRAM         VARCHAR(50),
    SUBJECT         VARCHAR(50),
    STUDENT_NUMBER  VARCHAR(15),
    FIRSTNAME       VARCHAR(50),
    LASTNAME        VARCHAR(50)
);

INSERT INTO TBL_1NF (YEAR, TERM, PROGRAM, SUBJECT, STUDENT_NUMBER, FIRSTNAME, LASTNAME)
VALUES
    ('2016-2017', '2ND', 'BSIT', 'ADVANCED DATABASE SYSTEM', '035-20130-0205', 'MAIRO', 'ELI'),
    ('2016-2017', '2ND', 'BSIT', 'MANAGEMENT INFORMATION SYSTEM', '035-20130-0205', 'MAIRO', 'ELI'),
    ('2016-2017', '2ND', 'BSIT', 'SYSTEMS ANALYSIS AND DESIGN', '035-20130-0205', 'MAIRO', 'ELI');


-- Create a new table for 2NF
CREATE TABLE TBL_2NF_PROGRAM (
    YEAR VARCHAR(10),
    TERM VARCHAR(4),
    PROGRAM VARCHAR(10),
    SUBJECT VARCHAR(50),
    PRIMARY KEY (YEAR, TERM, PROGRAM, SUBJECT)
);

CREATE TABLE TBL_2NF_STUDENT (
    STUDENT_NUMBER VARCHAR(15) PRIMARY KEY,
    FIRSTNAME VARCHAR(50),
    LASTNAME VARCHAR(50)
);

INSERT INTO TBL_2NF_PROGRAM (YEAR, TERM, PROGRAM, SUBJECT)
VALUES
    ('2016-2017', '2ND', 'BSIT', 'ADVANCED DATABASE SYSTEM'),
    ('2016-2017', '2ND', 'BSIT', 'MANAGEMENT INFORMATION SYSTEM'),
    ('2016-2017', '2ND', 'BSIT', 'SYSTEMS ANALYSIS AND DESIGN');

INSERT INTO TBL_2NF_STUDENT (STUDENT_NUMBER, FIRSTNAME, LASTNAME)
VALUES
    ('035-20130-0205', 'MAIRO', 'ELI');


-- Create a new table for 3NF
CREATE TABLE TBL_3NF_PROGRAM (
    PROGRAM VARCHAR(255) PRIMARY KEY
);

CREATE TABLE TBL_3NF_SUBJECTS (
    SUBJECT VARCHAR(255) PRIMARY KEY
);

CREATE TABLE TBL_3NF_STUDENTS (
    STUDENT_NUMBER VARCHAR(15) PRIMARY KEY,
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255)
);

CREATE TABLE TBL_3NF_YEAR (
    YEAR VARCHAR(10) PRIMARY KEY
);

INSERT INTO TBL_3NF_PROGRAM (PROGRAM)
VALUES ('BSIT');

INSERT INTO TBL_3NF_SUBJECTS (SUBJECT)
VALUES ('ADVANCED DATABASE SYSTEM'),
       ('MANAGEMENT INFORMATION SYSTEM'),
       ('SYSTEMS ANALYSIS AND DESIGN');

INSERT INTO TBL_3NF_STUDENTS (STUDENT_NUMBER, FIRSTNAME, LASTNAME)
VALUES ('035-20130-0205', 'MAIRO', 'ELI');

INSERT INTO TBL_3NF_YEAR (YEAR)
VALUES ('2016-2017 2ND');
